spring:
  datasource:
    name: test
    url: jdbc:postgresql://localhost:5434/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100

camel:
  springboot:
    main-run-controller: true
  threads:
    virtual:
      enabled: true
