spring:
  datasource:
    name: test
    url: jdbc:postgresql://localhost:5434/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 100
#      minimum-idle: 50
#  threads:
#    virtual:
#      enabled: true

camel:
  springboot:
    main-run-controller: true
  # Not working properly, inform -Dcamel.threads.virtual.enabled=true as JVM Argument.
#  threads:
#    virtual:
#      enabled: true

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(-%5p) %clr([%X{camel.breadcrumbId}][%X{camel.exchangeId}]){magenta} %clr(%applicationName[%15.15t]){faint} %clr(%40.40logger{39}:%L){cyan} %clr(:){faint} %m%n"
